# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/9f955791-5d56-460d-80d5-5dbd76620fc4";
    fsType = "btrfs";
    options = ["subvol=nixos"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/9f955791-5d56-460d-80d5-5dbd76620fc4";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/9f955791-5d56-460d-80d5-5dbd76620fc4";
    fsType = "btrfs";
    options = ["subvol=var"];
  };

  fileSystems."/root" = {
    device = "/dev/disk/by-uuid/9f955791-5d56-460d-80d5-5dbd76620fc4";
    fsType = "btrfs";
    options = ["subvol=home_root"];
  };

  fileSystems."/opt" = {
    device = "/dev/disk/by-uuid/9f955791-5d56-460d-80d5-5dbd76620fc4";
    fsType = "btrfs";
    options = ["subvol=opt"];
  };

  fileSystems."/home/ray" = {
    device = "/dev/disk/by-uuid/9f955791-5d56-460d-80d5-5dbd76620fc4";
    fsType = "btrfs";
    options = ["subvol=home_ray"];
  };

  fileSystems."/srv" = {
    device = "/dev/disk/by-uuid/9f955791-5d56-460d-80d5-5dbd76620fc4";
    fsType = "btrfs";
    options = ["subvol=srv"];
  };

  fileSystems."/usr/local" = {
    device = "/dev/disk/by-uuid/9f955791-5d56-460d-80d5-5dbd76620fc4";
    fsType = "btrfs";
    options = ["subvol=usr/local"];
  };

  fileSystems."/snapshots" = {
    device = "/dev/disk/by-uuid/9f955791-5d56-460d-80d5-5dbd76620fc4";
    fsType = "btrfs";
    options = ["subvol=snapshots"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7375-7BEB";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/mnt/artix" = {
    device = "/dev/disk/by-uuid/82d648d8-abe0-4abf-9795-134a911e9530";
    fsType = "btrfs";
  };

  fileSystems."/home/ray/files/2-disk" = {
    device = "/dev/disk/by-uuid/2e3dd481-982f-40dc-a811-28ed6e07ecbb";
    fsType = "btrfs";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/944c7f07-498c-4112-95ff-f8760c5ddbb9";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
