#!/bin/zsh

bindkey -e # emacs mode

# Configures bindings for jumping/deleting full and sub-words, similar to
# the keybindings in bash. https://unix.stackexchange.com/a/700029

# Jumping:
# Alt + B                Backward sub-word
# Ctrl + Alt + B         Backward full-word
# Alt + F                Forward sub-word
# Ctrl + Alt + F         Forward full-word

# Deleting:
# Ctrl + W               Backward delete full-word
# Ctrl + Alt + W         Backward delete sub-word
# Alt + D                Forward delete sub-word
# Ctrl + Alt + D         Forward delete full-word

# Which characters, besides letters and numbers, that are jumped over by a
# full-word jump:
FULLWORDCHARS="-.,[]~=/&:;!#$%^(){}<>'\""

backward-kill-full-word() { WORDCHARS=$FULLWORDCHARS zle .backward-kill-word ; }
backward-kill-sub-word() { WORDCHARS="" zle .backward-kill-word ; }
forward-kill-full-word() { WORDCHARS=$FULLWORDCHARS zle .kill-word ; }
forward-kill-sub-word() { WORDCHARS="" zle .kill-word ; }

zle -N backward-kill-full-word
zle -N backward-kill-sub-word
zle -N forward-kill-full-word
zle -N forward-kill-sub-word

bindkey "^[^w" backward-kill-full-word
bindkey "^w" backward-kill-sub-word
bindkey "^[d" forward-kill-sub-word
bindkey "^[^d" forward-kill-full-word

bindkey -r ^u
bindkey "^u" backward-kill-line		    # ctrl+u
bindkey "OH" beginning-of-line		# home
bindkey "OF" end-of-line				# end
bindkey "^[[1;5C" forward-word			# ctrl+right
bindkey "^[[1;5D" backward-word			# ctrl+left
bindkey "^[f" vi-forward-word			# alt+right
bindkey "^[b" vi-backward-word		   	# alt+left
bindkey "^[[3~" delete-char			    # delete
# edit command in $EDITOR
autoload -z edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line	    # ctrl+x ctrl+e
